<a href="https://colab.research.google.com/github/bharatikasture573-cyber/Task14_Bharti/blob/main/Task_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# Q1.
import numpy as np

# Create a 2D array of shape (5, 6) with random integers between 10 and 100
arr = np.random.randint(10, 101, size=(5, 6))
print("2D Array :",arr)

# Print array properties
print("Shape of The array : ",arr.shape)
print("Total Number of Elements : ",arr.size)
print("Data Type : ",arr.dtype)

2D Array : [[ 71  90  29  66  69  18]
 [ 56  66  55  10  90  79]
 [ 27  90  98  30  40 100]
 [ 29  35  75  81  78 100]
 [ 16  77  84  64  91  76]]
Shape of The array :  (5, 6)
Total Number of Elements :  30
Data Type :  int64


In [10]:
# Q2.
import numpy as np
arr = np.random.randint(1,51,size=20)
print("1D Array :",arr)

# Print statistical information
print("Minimum Value :",np.min(arr))
print("Index of Minimum Value :", np.argmin(arr))

print("Maximum Value :", np.max(arr))
print("Index of maximum value:", np.argmax(arr))

print("Sum of all elements:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))

1D Array : [15 17  8 40 10 34  1 49 23 42 27 35 23 19 37  9 43  1 16 44]
Minimum Value : 1
Index of Minimum Value : 6
Maximum Value : 49
Index of maximum value: 7
Sum of all elements: 493
Mean: 24.65
Standard Deviation: 14.68426028099475


In [19]:
# Q3.
import numpy as np
arr = np.random.randint(20,81,size=(4,5))
print("4*5 matrix :",arr)

print("Minimum Value :",np.min(arr))
print("Maximum Value :",np.max(arr))
print("Sum Of ALl Elements :",np.sum(arr))
print("Mean :",np.mean(arr))
print("Standard Deviation :",np.std(arr))

print("Sum Of Each Row :",np.sum(arr, axis=1))
print("Sum Of Each Column :",np.sum(arr, axis=0))


4*5 matrix : [[31 33 70 70 76]
 [70 73 67 57 78]
 [21 32 45 48 70]
 [60 72 48 72 36]]
Minimum Value : 21
Maximum Value : 78
Sum Of ALl Elements : 1129
Mean : 56.45
Standard Deviation : 17.61668243455617
Sum Of Each Row : [280 345 216 288]
Sum Of Each Column : [182 210 230 247 260]


In [27]:
# Q4.
import numpy as np
arr = np.arange(1,25)
print("Original Array :",arr)
print("Shape :",arr.shape)

# Reshape into (4, 6)
arr1 = arr.reshape(4,6)
print("\nArray Reshaped into (4,6) :")
print(arr1)
print("Shape:", arr1.shape)

# Reshape into (3, 8)
arr2 = arr.reshape(3,8)
print("\nArray Reshaped into (3,8) :")
print(arr2)
print("Shape:", arr2.shape)

#Reshape into (2,3,4)
arr3 = arr.reshape(2,3,4)
print("\nArray Reshaped into (2,3,4) :")
print(arr3)
print("Shape :",arr.shape)


Original Array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Shape : (24,)

Array Reshaped into (4,6) :
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)

Array Reshaped into (3,8) :
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
Shape: (3, 8)

Array Reshaped into (2,3,4) :
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape : (24,)


In [32]:
# Q5.
import numpy as np
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])
print("Original Array:")
print(arr)

print("\nFirst Row :",arr[0])
print("Last Column :",arr[:, 3])
print("Center 2x2 Submatrix:")
print(arr[1:3, 1:3])
print("Even Numbers :",arr[arr % 2 == 0])

Original Array:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

First Row : [10 20 30 40]
Last Column : [ 40  80 120]
Center 2x2 Submatrix:
[[ 60  70]
 [100 110]]
Even Numbers : [ 10  20  30  40  50  60  70  80  90 100 110 120]


In [37]:
# Q6.
import numpy as np
arr = np.random.randint(1, 101, size=(5, 5))
print("Original Matrix :")
print(arr)

print("Diagonal Elements :",np.diagonal(arr))
print("Elements Greater Than 50 :",arr[arr > 50])
arr[arr < 30] = 0
print("Modified Array :")
print(arr)

Original Matrix :
[[80 64 57 79 90]
 [71 96 80 99 45]
 [87 59 68 86 19]
 [28 84 97 95 78]
 [69 39 36 43 39]]
Diagonal Elements : [80 96 68 95 39]
Elements Greater Than 50 : [80 64 57 79 90 71 96 80 99 87 59 68 86 84 97 95 78 69]
Modified Array :
[[80 64 57 79 90]
 [71 96 80 99 45]
 [87 59 68 86  0]
 [ 0 84 97 95 78]
 [69 39 36 43 39]]


In [42]:
# Q7.
import numpy as np
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])
print("Array a :", a)
print("Array b :", b)

print("\nAddition :",a + b)
print("Subtraction :",a - b)
print("Multiplication :",a * b)
print("Division :",a / b)
print("Element-wise Power (a**b) :",a ** b)
print("Modulo Operation (a%b) :",a % b)

Array a : [10 20 30 40]
Array b : [1 2 3 4]

Addition : [11 22 33 44]
Subtraction : [ 9 18 27 36]
Multiplication : [ 10  40  90 160]
Division : [10. 10. 10. 10.]
Element-wise Power (a**b) : [     10     400   27000 2560000]
Modulo Operation (a%b) : [0 0 0 0]


In [45]:
# Q8.
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])
print("Matrix A:")
print(A)
print("Matrix B:")
print(B)

elementwise = A * B
print("\nElement-wise Multiplication:")
print(elementwise)

matrix = A @ B
print("\nMatrix Multiplication:")
print(matrix)

# Difference:
# (*) multiplies corresponding elements of the matrices.
# (@) or np.dot() performs actual matrix multiplication


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [49]:
# Q9.
import numpy as np
arr = np.random.randn(6, 6)
print("Original Matrix:")
print(arr)
print("\nShape :", arr.shape)
print("Size :", arr.size)
print("Data Type :", arr.dtype)

print("\nIndex of Maximum Value:", np.argmax(arr))
print("Index of Minimum Value:", np.argmin(arr))

print("\nTop Left 3x3 Submatrix:")
print(arr[:3, :3])

arr = np.abs(arr)
print("\nModified Matrix (Absolute Values):")
print(arr)
print("\nMean of Modified Matrix:", np.mean(arr))

Original Matrix:
[[-0.09076627  1.22357662 -1.15158386 -0.29425067  0.32297375 -0.43876173]
 [ 1.4600089   0.18778413  0.16396796  0.42406243  1.52293804  1.24268237]
 [-0.3692066   1.89445905  0.37551966  1.40455024  0.67866885 -0.99905681]
 [ 0.29598496 -0.07420958  0.5763964  -0.33679642  0.03063158 -0.4693952 ]
 [-0.02146767  0.17653012 -0.16248662 -1.78949614 -0.97559221 -1.00607894]
 [ 1.11013826  1.64948416 -1.09892914  1.33748148  0.6125227   0.27775022]]

Shape : (6, 6)
Size : 36
Data Type : float64

Index of Maximum Value: 13
Index of Minimum Value: 27

Top-Left 3x3 Submatrix:
[[-0.09076627  1.22357662 -1.15158386]
 [ 1.4600089   0.18778413  0.16396796]
 [-0.3692066   1.89445905  0.37551966]]

Modified Matrix (Absolute Values):
[[0.09076627 1.22357662 1.15158386 0.29425067 0.32297375 0.43876173]
 [1.4600089  0.18778413 0.16396796 0.42406243 1.52293804 1.24268237]
 [0.3692066  1.89445905 0.37551966 1.40455024 0.67866885 0.99905681]
 [0.29598496 0.07420958 0.5763964  0.33679642

In [50]:
# Q10.
import numpy as np

# Random marks between 30 and 100
marks = np.random.randint(30, 101, size=(10, 5))
print("Student Marks (10 x 5):")
print(marks)

# Calculate total marks of each student
total_marks = np.sum(marks, axis=1)

# Calculate average marks of each student
average_marks = np.mean(marks, axis=1)

# Print total and average
print("\nTotal Marks of Each Student:")
print(total_marks)

print("\nAverage Marks of Each Student:")
print(average_marks)

# Find highest and lowest total marks
highest = np.argmax(total_marks)
lowest = np.argmin(total_marks)

print("\nStudent with Highest Total Marks: Student", highest + 1)
print("Highest Total Marks:", total_marks[highest])

print("\nStudent with Lowest Total Marks: Student", lowest + 1)
print("Lowest Total Marks:", total_marks[lowest])

# Calculate overall class statistics
print("\nOverall Class Mean:", np.mean(marks))
print("Overall Class Standard Deviation:", np.std(marks))

# Reshape the array (Demonstration)
reshaped = marks.reshape(5, 10)

print("\nReshaped Array (5 x 10):")
print(reshaped)

# Extract marks of top 3 students
top3 = np.argsort(total_marks)[-3:][::-1]

print("\nTop 3 Students (Based on Total Marks):")
print(top3 + 1)

print("\nMarks of Top 3 Students:")
print(marks[top3])

Student Marks (10 x 5):
[[41 51 67 94 77]
 [53 91 88 97 71]
 [89 59 36 92 50]
 [33 59 51 73 72]
 [60 59 36 52 99]
 [66 76 57 90 94]
 [84 34 52 60 80]
 [81 98 39 84 87]
 [46 98 45 35 83]
 [82 74 48 62 65]]

Total Marks of Each Student:
[330 400 326 288 306 383 310 389 307 331]

Average Marks of Each Student:
[66.  80.  65.2 57.6 61.2 76.6 62.  77.8 61.4 66.2]

Student with Highest Total Marks: Student 2
Highest Total Marks: 400

Student with Lowest Total Marks: Student 4
Lowest Total Marks: 288

Overall Class Mean: 67.4
Overall Class Standard Deviation: 19.942918542680758

Reshaped Array (5 x 10):
[[41 51 67 94 77 53 91 88 97 71]
 [89 59 36 92 50 33 59 51 73 72]
 [60 59 36 52 99 66 76 57 90 94]
 [84 34 52 60 80 81 98 39 84 87]
 [46 98 45 35 83 82 74 48 62 65]]

Top 3 Students (Based on Total Marks):
[2 8 6]

Marks of Top 3 Students:
[[53 91 88 97 71]
 [81 98 39 84 87]
 [66 76 57 90 94]]
